###
GET http://localhost:3000/client

###
POST http://localhost:3000/client
Content-Type: application/json

{
    "name":"Joaoo",
    "surname":"ALves",
    "company": "It",
    "status": true,
    "phone": 922356482
}

###
PUT http://localhost:3000/client/513a581d-05aa-4d43-bb94-f2253221d5b0
Content-Type: application/json

{
    "name":"Robertoo",
    "status": false
}

###
DELETE  http://localhost:3000/client/d08867e1-c77f-44dd-a46f-17bceeb2d72a

